### PR TITLE
Add types for typescript users

### PR DESCRIPTION
**Pull request by 123joshuawu**
appreciate the package, very useful.

Had these defined locally, but opening a PR so others in the future would be able to use this package in TypeScript without extra configuration.

### CODE REVIEW

**Comment by tremby** [comment]
Lovely, thanks!

Can you just verify that the type for the options is correct? There's a true in the type; should that not say boolean? Does it allow for the option being absent (like just an empty object being passed), and for the options object not to be passed at all?

**Comment by tremby** [comment]
Also, I see the return type is an array of objects, but according to the readme (I haven't used this in a while!) members could be other JSON types.

**Comment by 123joshuawu** [comment]
> Lovely, thanks!
> 
> Can you just verify that the type for the options is correct? There's a true in the type; should that not say boolean? Does it allow for the option being absent (like just an empty object being passed), and for the options object not to be passed at all?

Added `options?: { partial?: false }` to cover the cases you described. 

I chose to use overloading instead of `boolean` so it can type check the existence of the `remainder` property based on the parameters.

Screenshot 2023-05-27 at 11 47 53 PM



> Also, I see the return type is an array of objects, but according to the readme (I haven't used this in a while!) members could be other JSON types.

Added generic so user can override the return type. The default is `object[]` which aligns with the jsdoc.

```
jsonMultiParse('') // object[]
jsonMultiParse<string>('') // string[]
```

**Comment by tremby** [comment]
Sounds good, thanks.

> Added generic so user can override the return type. The default is `object[]` which aligns with the jsdoc.

I like the idea of a generic, to be used if the developer is certain of what kind of data will be coming in, but the JSdoc was wrong. I'll merge and then tweak.

Thank you!

**Comment by tremby** [comment]
It came to my attention today that I forgot to publish this to NPM at the time. It's now published with 1.3.1.

**Pull request merged**
